# Visual & Layout Options
legacy_layout=0
position=top-left
table_columns=3
font_size=24
width=400

# Keybindings
toggle_hud=Page_Up

# Performance
vsync=1
gl_vsync=0
fps_limit=0
fps_limit_method=late

# Colours 
gpu_color=2E9762
cpu_color=2E97CB
vram_color=AD64C1
ram_color=C26693
engine_color=FF0069
frametime_color=00FF00

# CPU Stats
cpu_text=CPU
cpu_stats
cpu_mhz
cpu_temp
cpu_power

# GPU stats
gpu_text=GPU
gpu_stats
gpu_core_clock
gpu_temp
gpu_power

# Vram and ram
vram
gpu_mem_clock

ram

# FPS and Frametime
custom_text=

fps
fps_metrics=0.01
frametime=0

frame_timing

# Other info
custom_text=
exec=cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2

custom_text=
exec=glxinfo -B | awk -F': ' '/Device/ {print $2}' | sed 's/ (.*//' 

custom_text= 
exec=awk -F': ' '/model name/ {print $2; exit}' /proc/cpuinfo | sed -E 's/ [0-9]+-Core Processor$//'

custom_text=
custom_text=
exec=command -v gamemoded >/dev/null 2>&1 && gamemoded -s || echo "GameMode N/A"
