-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'preload = ~/.config/hypr/wallpapers/archlinux.png' has no enclosing section
-- TODO: manual review — top-level key 'wallpaper = ,~/.config/hypr/wallpapers/archlinux.png' has no enclosing section
