-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local font = "Monospace"

-- TODO: manual review — unknown section 'auth {' on line 7

-- TODO: manual review — unknown section 'background {' on line 20

-- TODO: manual review — unknown section 'input-field {' on line 26

-- TODO: manual review — unknown section 'label {' on line 51

-- TODO: manual review — unknown section 'label {' on line 62

hl.config({
    general = {
        hide_cursor = true,
    },
    animations = {
        enabled = false,
    },
})

