-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "elan0676:00-04f3:3195-touchpad",
    enabled = true,
    sensitivity = 0.5,
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
hl.config({
    input = {
        kb_layout = "gb",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0,
        accel_profile = "flat",
        touchpad = {
            natural_scroll = false,
            disable_while_typing = true,
        },
    },
    misc = {
        middle_click_paste = false,
    },
    -- archPPxP14s Trackpad
})

