-- Binds windows key
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"

--# App Keybinds
    -- Thunar
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("thunar"))
    -- Terminal
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
    -- Firefox
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("firefox"))
    -- App Manager
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("rofi -show drun"))
    -- Obsidian
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("obsidian"))
    -- Vscode
--   bind = $mainMod, V, exec, uwsm app -- code
    -- Discord
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("discord"))
    -- Thunderbird
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("thunderbird"))

-- Hyprlock and Exit Hyprland
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + CTRL + SHIFT + L", hl.dsp.exec_cmd("exit"))

--# Kill and Show Waybar
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("pkill waybar"))
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("waybar"))

--# Screenshot
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region -o ~/Pictures/"))

--# Tiling/Window Keybinds
    -- Kill Focused Window
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
    -- Force Kill Focused Window
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("kill -9 $(hyprctl activewindow | grep pid | awk '{print $2}')"))
    -- Toggle Floating
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
    -- Toggle Pseudotiling
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
    -- Toggle Split
--bind = $mainMod, U, togglesplit, # dwindle
    -- Fullscreen
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }))

    -- Example special workspace (scratchpad)
hl.bind(mainMod .. " + A", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.window.move({ workspace = "special:magic" }))


--# Other
    -- Exit Hyprlands
    --bind = $mainMod, L, exit,

--# Laptop Multimedia Keys
    -- Increase Vol by 1%
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +1%"), { locked = true })
    -- Decrease Vol by 1%
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -1%"), { locked = true })
    -- Increase Brightness by 5%
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 5%+"), { locked = true, repeating = true })
    -- Decrease Brightness by 5%
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"), { locked = true, repeating = true })
    -- Other
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })

-- Switch Windows
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Switch Switch Workspaces
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Go up or down a workspace
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.focus({ workspace = "e+1" }))

-- Move Active Window to Workspace 
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
