-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.config({
    master = {
        new_status = "master",
    },
    misc = {
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = 1, -- If true disables the random hyprland logo / anime girl background. :(
    },
    -- Remove scaling for xWayland apps
    xwayland = {
        force_zero_scaling = true,
    },
})

