--# Boot Apps
        --exec-once = uwsm app -- discord
	--exec-once = uwsm app -- spotify
	--exec-once = uwsm app -- firefox
	--exec-once = uwsm app -- obsidian
	--exec-once = uwsm app -- steam
	--exec-once = uwsm app -- lutris
	--exec-once = uwsm app -- cable
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Notification Daemon

-- Hyprswitch Daemon

-- Wallpapers

-- App Launcher (replaced with wofi)
-- exec-once = uwsm app -- walker -- gapplication-service

-- Authentication Agent

-- Udiskie (auto USB mounter)

hl.on("hyprland.start", function()
    hl.exec_cmd("kitty", { workspace = "5 silent" })
    hl.exec_cmd("uwsm app -- dunst")
    hl.exec_cmd("hyprshell run &")
    hl.exec_cmd("uwsm app -- hyprpaper")
    hl.exec_cmd("exec-once = systemctl --user start hyprpolkitagent")
    hl.exec_cmd("systemctl --user enable --now hyprpolkitagent.service")
    hl.exec_cmd("udiskie &")
end)

