hl.on("hyprland.start", function()
    hl.exec_cmd("kitty", { workspace = "5 silent" })
    hl.exec_cmd("dunst")
    hl.exec_cmd("hyprshell run")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("waybar") 
    hl.exec_cmd("openrgb")
end)

