-- Ignore maximize requests from apps. You'll probably like this.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "*",
    },
    suppress_event = "maximize",
})

-- Pavucontrol always floating
hl.window_rule({
    match = {
        class = "org.pulseaudio.pavucontrol",
    },
    float = true,
    size = "960 720",
})

