-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
    workspace = "special:magic",
    ["on-created-empty"] = "blur:enable",
    blur = "size 100",
    blur = "passes 3",
})

